# Generated by Django 4.2.24 on 2025-10-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
