# Generated by Django 4.2.24 on 2025-10-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='base_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='pizza.base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping_id',
            field=models.ManyToManyField(blank=True, to='pizza.topping'),
        ),
    ]
