# Generated by Django 4.2.24 on 2025-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizza_base_id_pizza_topping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping_id',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='pizza.topping'),
        ),
    ]
