# Generated by Django 4.2.24 on 2025-10-05 17:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_alter_pizza_topping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
