# Generated by Django 4.2.24 on 2025-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_pizza_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='num_order',
            field=models.IntegerField(default=0),
        ),
    ]
